### ISSUE TITLE
Decorate a method with block parameter

### ISSUE THREAD

**Issue by Ishotihadus** [kjleitz/adornable#13]
Hello. This library is very cool and convenient, and I use it in my project.

I'm wondering how to decorate a method that receives a block.

For example:

```rb
require 'adornable'

class Test
  extend Adornable
  decorate :log
  def method1(value)
    value
  end
  decorate :log
  def method2(value)
    yield(value)
  end
end

test = Test.new

test.method1('value') # ok
# Calling method `Test#method1` with arguments `["value"]`
# => "value"

test.method2(:value){|e| e.to_s} # ?
# Calling method `Test#method2` with arguments `[:value]`
# (irb):10:in `method2': no block given (yield) (LocalJumpError)
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/adornable-1.3.0/lib/adornable/utils.rb:44:in `call'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/adornable-1.3.0/lib/adornable/utils.rb:44:in `empty_aware_send'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/adornable-1.3.0/lib/adornable/machinery.rb:93:in `run_decorators'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/adornable-1.3.0/lib/adornable/machinery.rb:125:in `block in run_decorators'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/adornable-1.3.0/lib/adornable/decorators.rb:18:in `log'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/adornable-1.3.0/lib/adornable/utils.rb:44:in `empty_aware_send'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/adornable-1.3.0/lib/adornable/machinery.rb:124:in `run_decorators'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/adornable-1.3.0/lib/adornable/machinery.rb:43:in `run_decorated_instance_method'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/adornable-1.3.0/lib/adornable.rb:46:in `block in method_added'
#         from (irb):15:in `<main>'
#         from <internal:kernel>:187:in `loop'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/gems/3.3.0/gems/irb-1.11.0/exe/irb:9:in `<top (required)>'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/bin/irb:25:in `load'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/bin/irb:25:in `<top (required)>'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `load'
#         from /Users/ishotihadus/.rbenv/versions/3.3.1/lib/ruby/3.3.0/bundler/cli/exec.rb:58:in `kernel_load'
#         ... 13 levels...
```

Is there any solution or workaround?

Thank you in advance.

P.S. This error also appears in Ruby 2.5 and 3.2.

**Comment by Ishotihadus** [comment]
I just created PR #14
